In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [5]:
b=np.array([[8,9,10],[11,12,13]])
print(b)

[[ 8  9 10]
 [11 12 13]]


In [7]:
c=np.array([[[27,36,16],[2,3,4],[18,19,27]]])
print(c)

[[[27 36 16]
  [ 2  3  4]
  [18 19 27]]]


In [9]:
arr=np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
arr=np.ones((1,3))
print(arr)

[[1. 1. 1.]]


In [15]:
arr=np.arange(5,10,2)
print(arr)

[5 7 9]


In [17]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [29]:
print(arr.ndim)

2


In [31]:
print(arr.size)

6


In [33]:
print(arr.dtype)

int64


In [35]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [37]:
print(arr[-1])

40


In [39]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [41]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [43]:
print(arr[:3])
print(arr[3:])

[10 20 30]
[40 50 60]


In [45]:
print(arr[::2])

[10 30 50]


In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [49]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,3,2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [59]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [61]:
arr=np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]
