In [1]:
import numpy as np

In [3]:
arr=np.array([4,5,6,7,8])
print(arr.shape)

(5,)


In [5]:
print(arr.size)
print(arr.dtype)

5
int32


In [7]:
#program 3
#create
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr[0:10])
print(arr[15:])
print(arr[:5])

[ 1  2  3  4  5  6  7  8  9 10]
[16 17 18 19 20]
[1 2 3 4 5]


In [13]:
#program 4
#create an array of 12 elements and reshape it into 3 x 4 and 2 x 6
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,6)
print(new_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
# program 5
#perform addition,subtraction,multiplication and division operations on to arrays
a=np.array([1,2,3])
b=np.array([4,6,7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 5  8 10]
[-3 -4 -4]
[ 4 12 21]
[0.25       0.33333333 0.42857143]
